name = "events-signup-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "events-signup"
database_id = "ba7984db-a257-42d8-acdd-4b188c6273aa"

[[kv_namespaces]]
binding = "SESSIONS"
id = "f509d1c9af9f45eabb455b7e4ea4945e"
preview_id = "f509d1c9af9f45eabb455b7e4ea4945e"

[vars]
ALLOWED_ORIGIN = "https://events.npole.org"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
